server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/linkme?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: localhost
#    port: 6379
#    timeout: 2000ms
#    lettuce:
#      pool:
#        max-active: 0
#        max-idle: 0
#        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.linkme.backend.entity

jwt:
  secret: change_this_secret_to_a_strong_one_change_this_secret
  expire-seconds: 86400

logging:
  level:
    root: INFO
    org.springframework.data.redis: WARN
